export const majorOptions = [
  { label: 'Accounting & finance', value: 'accounting_finance' },
  { label: 'Agriculture, forestry & food', value: 'agriculture_forestry_food' },
  { label: 'American studies', value: 'american_studies' },
  { label: 'Anatomy & physiology', value: 'anatomy_physiology' },
  { label: 'Anthropology', value: 'anthropology' },
  { label: 'Architecture', value: 'architecture' },
  { label: 'Art', value: 'art' },
  { label: 'Biosciences', value: 'biosciences' },
  { label: 'Building and town and country planning', value: 'town_planning' },
  {
    label: 'Business, management & marketing',
    value: 'business_management_marketing',
  },
  { label: 'Chemistry', value: 'chemistry' },
  { label: 'Classics & ancient history', value: 'classics_ancient_history' },
  {
    label: 'Computer science & information systems',
    value: 'computer_science_information_systems',
  },
  { label: 'Criminology', value: 'criminology' },
  { label: 'Dentistry', value: 'dentistry' },
  { label: 'Design & crafts', value: 'design_crafts' },
  { label: 'Drama & dance', value: 'drama_dance' },
  { label: 'Earth & marine sciences', value: 'earth_marine_sciences' },
  { label: 'Economics', value: 'economics' },
  { label: 'Education', value: 'education' },
  { label: 'Engineering: chemical', value: 'engineering_chemical' },
  { label: 'Engineering: civil', value: 'engineering_civil' },
  {
    label: 'Engineering: electronic & electrical',
    value: 'engineering_electronic_electrical',
  },
  { label: 'Engineering: general', value: 'engineering_general' },
  {
    label: 'Engineering: materials & mineral',
    value: 'engineering_materials_mineral',
  },
  { label: 'Engineering: mechanical', value: 'engineering_mechanical' },
  { label: 'English & creative writing', value: 'english_creative_writing' },
  { label: 'Fashion & textiles', value: 'fashion_textiles' },
  {
    label: 'Film production & photography',
    value: 'film_production_photography',
  },
  {
    label: 'Forensic science & archaeology',
    value: 'forensic_science_archaeology',
  },
  {
    label: 'Geography & environmental studies',
    value: 'geography_environmental_studies',
  },
  { label: 'Health professions', value: 'health_professions' },
  { label: 'History', value: 'history' },
  { label: 'History of art', value: 'history_of_art' },
  {
    label: 'Hospitality, event management & tourism',
    value: 'hospitality_event_management_tourism',
  },
  {
    label: 'Journalism, publishing & public relations',
    value: 'journalism_publishing_public_relations',
  },
  { label: 'Law', value: 'law' },
  { label: 'Mathematics', value: 'mathematics' },
  { label: 'Media & film studies', value: 'media_film_studies' },
  { label: 'Medicine', value: 'medicine' },
  {
    label: 'Modern languages & linguistics',
    value: 'modern_languages_linguistics',
  },
  { label: 'Music', value: 'music' },
  { label: 'Nursing & midwifery', value: 'nursing_midwifery' },
  { label: 'Pharmacy & pharmacology', value: 'pharmacy_pharmacology' },
  { label: 'Philosophy', value: 'philosophy' },
  { label: 'Physics', value: 'physics' },
  { label: 'Politics', value: 'politics' },
  { label: 'Psychology', value: 'psychology' },
  {
    label: 'Religious studies and theology',
    value: 'religious_studies_theology',
  },
  {
    label: 'Social policy & administration',
    value: 'social_policy_administration',
  },
  { label: 'Social work', value: 'social_work' },
  { label: 'Sociology', value: 'sociology' },
  { label: 'Sports science', value: 'sports_science' },
  { label: 'Veterinary science', value: 'veterinary_science' },
];
