export const EIconName = {
  Arrow_Right: 'Arrow_Right',
  American_Flag: 'American_Flag',
  ArtDesign: 'Art_Design',
  Business: 'Business',
  Class: 'Class',
  Compare: 'Compare',
  ComputerScience: 'Computer_Science',
  Education: 'Education',
  Education_V2: 'Education_V2',
  Engineering: 'Engineering',
  Exit: 'Exit',
  Facebook: 'Facebook',
  Favorite: 'Favorite',
  Twitter: 'Twitter',
  Instagram: 'Instagram',
  Likedine: 'Likedine',
  Law: 'Law',
  Loud: 'Loud',
  Music: 'Music',
  Partner: 'Partner',
  Pharmacy: 'Pharmacy',
  Home: 'Home',
  UK_Flag: 'UK_Flag',
  Ireland_Flag: 'Ireland_Flag',
  Idea: 'Idea',
  Australlia_Flag: 'Australlia_Flag',
  Vietnam_Flag: 'Vietnam_Flag',
  Scholarship: 'Scholarship',
  ScholarshipResult: 'Scholarship_Result',
  SocialWork: 'SocialWork',
  StudyAboard: 'StudyAboard',
  Subscribe: 'Subscribe',
  Visa: 'Visa',
};
export const EIconColor = {
  STYLE_10: '#22458F',
  WHITE: '#FFF',
};
